-- Create table for Fixed Broadband data
CREATE DATABASE Broadbanddata;
USE Broadbanddata;
DROP DATABASE Broadbanddata;
CREATE TABLE Broadbanddata (
    BID INT,
    RankChange VARCHAR(10),
    Country VARCHAR(100),
    Mbps FLOAT
);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES (1, '+2', 'Iceland', 388.20);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES (2, '-1', 'Singapore', 386.42);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES (3, '-1', 'France', 378.18);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES (4, '+1', 'Hong Kong (SAR)', 357.70);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES (5, '-1', 'Monaco', 348.71);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(6,'	-', 'Switzerland',	341.58);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(7,	'1',	'Chile',	341.05);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(8	,'-1',	'United Arab Emirates',	330.57);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(9	,'2',	'Denmark',	318.68);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(10,	'3',	'United States',	312.22);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(11,	'1',	'Japan'	,311.56);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(12,	'-3',	'China'	,306.66);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(13,	'1'	,'Romania',	305.53);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(14,	'2'	,'Thailand',	301.73);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(15,	'-'	,'Spain'	,301.63);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(16,	'1'	,'Hungary',	299.59);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(17,	'2'	,'Israel'	,297.84);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(18,	'-'	,'Canada'	,296.76);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(19,	'-9'	,'Liechtenstein'	,291.71);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(20,	'1'	,'Qatar'	,282.49);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(21,	'-1'	,'Netherlands',	279.63);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(22,	'2'	,'Portugal'	,259.63);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(23,	'11'	,'Andorra'	,258.31);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(24,	'3'	,'New Zealand',	252.31);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(25,	'-','Luxembourg'	,250.11);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(26,	'2',	'Poland'	,245.85);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(27,	'-4',	'Moldova'	,241.88);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(28,	'1'	,'Sweden'	,239.18);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(29,	'1'	,'Macau (SAR)',	238.88);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(30,	'1',	'Lithuania'	,230.29);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(31,	'1',	'Malta'	,228.23);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(32,	'1',	'Brazil'	,226.65);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(33	,'5',	'Uruguay'	,225.5);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(34,	'1',	'Taiwan'	,223.03);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(35,	'-13',	'South Korea',	221.81);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(36,	'5'	,'Latvia'	,220.44);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(37,	'-'	,'Norway'	,220.05);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(38,	'-2'	,'Panama'	,217.9);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(39,	'9'	,'Vietnam',	217.08);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(40,	'-14'	,'San Marino',	217.07);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(41,	'-1'	,'Finland'	,216.79);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(42,	'2'	,'Peru'	,212.76);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(43,	'-4'	,'Kuwait'	,211.7);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(44,	'-2'	,'Italy'	,209.83);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(45,	'-'	,'Ireland',	206.06);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(46,	'1'	,'Colombia',	205.71);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(47,	'-4'	,'Belgium'	,205.65);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(48,	'1'	,'Slovenia'	,202.56);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(49,	'2'	,'Malaysia'	,202.41);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(50,	'-4'	,'United Kingdom',	200.8);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(51,	'1'	,'Slovakia'	,200.53);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(52,	'-2'	,'Jordan'	,198.05);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(53,	'1'	,'Philippines',	171.11);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(54,	'-1'	,'Germany'	,169.81);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(55,	'8'	,'Saint Lucia',	168.32);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(56,	'-'	,'Austria'	,167.49);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(57,	'1'	,'Barbados'	,166.5);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(58,	'-1'	,'Saudi Arabia',	162.28);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(59,	'-4'	,'Croatia'	,162.18);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(60,	'1'	,'Bulgaria'	,152.46);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(61,	'11'	,'Ecuador'	,151.63);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(62,	'-3',	'Czechia'	,150.78);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(63,	'-1'	,'Trinidad and Tobago',	149.8);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(64,	'-4',	'Serbia'	,149.27);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(65,	'3',	'Argentina',	145.49);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(66,	'-1',	'Russia'	,145.34);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(67,	'-3	','Cyprus'	,142.24);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(68,	'5',	'Ukraine'	,141.54);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(69,	'-2',	'Montenegro'	,141.42);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(70,	'-4',	'Guyana'	,141.1);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(71,	'-',	'Saint Vincent and the Grenadines',	136.89);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(72,	'-3',	'Grenada'	,134.97);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(73,	'1',	'Costa Rica',	132.68);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(74,	'-4',	'Dominica'	,132.25);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(75,	'-',	'Australia'	,129.66);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(76,	'-',	'Estonia'	,128.57);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(77,	'7',	'Oman'	,123.84);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(78,	'-1',	'Paraguay',	123.47);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(79,	'-1',	'Brunei'	,120.8);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(80,	'1',	'CÃ´te dIvoire',	116.04);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(81,	'-1',	'Belarus'	,112.81);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(82,	'-3',	'Bahrain'	,111.58);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(83,	'-',	'The Bahamas',	110.46);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(84,	'-2',	'Albania'	,109.12);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(85,	'-',	'Mexico'	,107.36);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(86,	'3',	'Jamaica'	,104.45);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(87,	'-',	'Armenia'	,102.86);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(88,	'-',	'Kosovo'	,101.81);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(89,	'-3',	'Turkey	',98.69);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(90,	'2',	'India'	,94.91);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(91,	'-',	'Nepal'	,93.75);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(92,	'-2',	'Kazakhstan',	93.51);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(93,	'1',	'Uzbekistan'	,92.58);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(94,	'2',	'Venezuela'	,90.14);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(95,	'2',	'Greece'	,88.48);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(96,	'-1',	'Palestine',	87.29);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(97,	'2',	'Mauritius',	84.27);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(98,	'4',	'Belize'	,83.67);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(99	,'-6',	'Saint Kitts and Nevis',	83.62);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(100,	'-',	'South Africa'	,82.42);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(101,	'-3',	'Ghana'	,80.74);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(102,	'-1',	'Mongolia'	,80.29);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(103,	'2',	'North Macedonia',	76.04);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(104,	'19',	'Seychelles'	,74.28);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(105,	'-2',	'Nicaragua'	,73.88);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(106,	'4',	'Egypt'	,73.43);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(107,	'-3',	'Guatemala',	72.48);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(108,	'-1',	'El Salvador',	71.89);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(109,	'-',	'Kyrgyzstan',	71.77);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(110,	'-2',	'Bangladesh',	71.7);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(111,	'-5',	'Bosnia and Herzegovina',	70.02);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(112,	'12',	'Lebanon'	,65.37);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(113,	'-1',	'Burkina Faso',	61.45);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(114,	'-1',	'Cambodia'	,60.61);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(115,	'-4',	'Gabon'	,59.9);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(116,	'1',	'Azerbaijan',	58.87);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(117,	'-3',	'Dominican Republic'	,58.36);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(118,	'1'	,'Sri Lanka'	,56.57);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(119,	'26',	'Algeria'	,56.21);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(120,	'-2',	'DR Congo',	55.76);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(121,	'-5',	'Congo',	55.19);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(122,	'-1',	'Honduras',	54.84);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(123,	'-1',	'Laos',	54.33);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(124,	'-9',	'Haiti',	54.07);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(125,	'2',	'Tajikistan',	53.05);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(126,	'-',	'Iraq'	,48.66);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(127,	'17',	'Zimbabwe',	46.93);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(128,	'5',	'Antigua and Barbuda',	46.47);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(129,	'2',	'Senegal'	,46.46);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(130,	'-',	'Indonesia',	46.04);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(131,	'-3',	'Rwanda	',45.7);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(132,	'2',	'Morocco'	,44.15);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(133,	'-1',	'Bolivia'	,43.75);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(134,	'2',	'Nigeria'	,42.94);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(135,	'-6',	'Togo'	,42.23);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(136,	'1',	'Western Sahara',	42.16);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(137,	'-12',	'Madagascar'	,41.96);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(138,	'1',	'Lesotho'	,39.82);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(139,	'10',	'Niger'	,38.02);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(140,	'6',	'Ethiopia'	,37.66);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(141,	'-1',	'Djibouti'	,37.41);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(142,	'-',	'Angola'	,37.02);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(143,	'5',	'Somalia'	,36.7);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(144,	'-3',	'Swaziland',	36.21);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(145,	'-7',	'Zambia'	,35.97);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(146,	'9',	'Maldives',	34.98);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(147,	'-12',	'Malawi'	,34.92);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(148,	'8',	'Fiji'	,34.62);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(149,	'5',	'Mauritania',	34.58);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(150,	'3',	'Georgia'	,34.53);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(151,	'1',	'Iran'	,34.29);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(152,	'-2',	'Benin'	,34.19);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(153,	'-6',	'Bhutan'	,34.17);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(154,	'-11',	'Tanzania',	33.67);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(155,	'4',	'Sierra Leone',	32.16);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(156,	'5',	'Mozambique'	,30.97);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(157,	'1'	,'Sudan'	,30.7);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(158,	'-1',	'Myanmar (Burma)',	30.69);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(159,	'3'	,'Mali'	,30.56);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(160,	'14'	,'Guinea',	30.32);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(161,	'-10',	'Papua New Guinea',	29.74);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(162,	'1',	'Uganda',	29.19);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(163,	'5',	'Cameroon',	28.82);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(164,	'-',	'Suriname',	27.31);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(165,	'-',	'Cape Verde',	26.61);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(166,	'1',	'Namibia'	,26.05);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(167,	'-7',	'Libya'	,23.71);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(168,	'3',	'Pakistan',	23.31);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(169,	'1',	'Turkmenistan',	23.15);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(170,	'-1',	'Kenya'	,22.78);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(171,	'-5',	'Vanuatu'	,22.45);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(172,	'-',	'Botswana',	22.22);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(173,	'-',	'East Timor',	21.17);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(174,	'2',	'Syria'	,18.69);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(175,	'-',	'Liberia'	,17.64);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(176,	'1',	'Yemen'	,16.26);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(177,	'1',	'Tunisia'	,15.69);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(178	,'1',	'The Gambia',	15.52);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(179,'1',	'Burundi',	11.07);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(180,	'2',	'Afghanistan',	10.21);
INSERT INTO BroadbandData (BID, RankChange, Country, Mbps) VALUES(181	,'-' ,'Cuba',	8.36);
select * from BroadbandData;