-- Create table for Mobile data
DROP DATABASE Mobiledata;
CREATE DATABASE Mobiledata;
USE Mobiledata;
CREATE TABLE MobileData (
    MID INT,
    RankChange VARCHAR(10),
    Country VARCHAR(100),
    Mbps FLOAT
);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (1, '+1', 'Qatar', 472.18);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (2, '-1', 'United Arab Emirates', 439.73);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (3, '-', 'South Korea', 294.53);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (4, '+1', 'Iceland', 284.29);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (5, '-1', 'Kuwait', 283.98);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (6,	'-','Macau (SAR)',	243.42);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (7,	'-', 'Denmark', 243.28);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES( 8,	'-','United States',	232.83);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(9,	'7',	'Norway',	219.8);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(10,	'-1',	'Saudi Arabia',	217.42);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(11,	'-',	'Bahrain',	214.95);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (12,	'3',	'Portugal',	200.22);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (13,   '-1',	'Singapore',	197.24);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (14,	'-4',	'Bulgaria',	196.03);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (15,	'-1',	'Malaysia',	193.83);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (16,	'-3',	'China',	187.82);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (17,	'5',	'Brazil',	182.58);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (18,	'1',	'Sweden',	179.01);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (19,	'-1',	'India',	178.98);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(20,	'-',	'Croatia',	175.6);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(21,	'4'	,'Cyprus',	174.7);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(22,	'2'	,'France	',173.08);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(23,	'3'	,'Switzerland',	170.97);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(24,	'-7'	,'Lithuania'	,170.96);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (25,	'-2'	,'North Macedonia'	,170.12);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (26	,'-5'	,'Uruguay'	,169.57);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(27	,'1'	,'Finland'	,165.54);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (28	,'5','	Estonia'	,163.45);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (29	,'1'	,'Greece	',162.53);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (30	,'2'	,'Australia'	,155.08);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (31	,'-4	','New Zealand',	154.38);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (32	,'-3	','Canada'	,151.89);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (33	,'-2	','Netherlands',	149.01);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (34	,'1'	,'Latvia'	,149);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (35	,'1	','Brunei	',148.24);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES (36	,'-2	','Malta'	,147.84);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(37	,'-'	,'Luxembourg'	,144.98);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(38	,'1	','Taiwan	',144.3);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(39	,'-1'	,'Belgium',	143.65);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(40	,'-'	,'Oman	',135.02);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(41	,'2'	,'Spain	',133.9);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(42	,'-'	,'Maldives',	131.49);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(43	,'-2	','Slovenia',	129.41);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(44	,'6'	,'Mauritius',	124.62);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(45	,'-1'	,'Germany	',123.66);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(46	,'-'	,'Poland'	,122.82);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(47	,'-2'	,'Hong Kong (SAR)'	,120.48);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(48	,'4'	,'Austria	',116.83);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(49	,'4'	,'Czechia	',115.99);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(50	,'-2	','Kosovo	',115.63);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(51	,'-'	,'United Kingdom'	,113.46);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(52	,'-5'	,'Ethiopia',	112.5);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(53	,'-4','Dominican Republic',	105.4);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(54	,'4'	,'Kazakhstans'	,104.82);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(55	,'2'	,'Israel	',103.21);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(56	,'-2'	,'Montenegro',	101.82);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(57	,'-1'	,'Italy	',101.61);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(58	,'-3	','South Africa',	101.2);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(59	,'1'	,'Hungary	',99.38);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(60	,'-1'	,'Romania	',97.85);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(61	,'2'	,'Guatemala	',97.07);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(62	,'-'	,'Ireland	',97.07);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(63	,'-2'	,'Slovakia	',91.9);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(64	,'1'	,'Thailand	',87.83);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(65	,'1'	,'Botswana'	,87.06);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(66	,'-2'	,'Japan	',86.02);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(67	,'19	','Senegal',	82.83);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(68	,'-'	,'Chile	',79.66);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(69	,'2	','Suriname',	77.37);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(70	,'-3'	,'Nigeria',	74.43);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(71	,'-1	','Philippines',	73.23);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(72	,'-3'	,'Albania	',72.78);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(73	,'8'	,'Uganda	',72.56);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(74	,'15	','Zimbabwe',	71.92);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(75	,'-3	','Serbia'	,67.72);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(76	,'3	','Turkey	',67.01);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(77	,'-1'	,'Uzbekistan',	64.41);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(78	,'-5	','Azerbaijan'	,64.08);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(79	,'-5	','Mexico'	,63.06);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(80	,'-5'	,'Vietnam',	62.54);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(81	,'6',	'Guyana	',62.5);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(82	,'-4'	,'Colombia',	61.11);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(83	,'-'	,'Morocco',	60.62);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(84	,'-'	,'Georgia',	60.12);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(85	,'-5	','Iran	',58.74);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(86	,'4'	,'Argentina',	57.16);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(87	,'1'	,'Kenya'	,56.26);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(88	,'3'	,'Costa Rica'	,56.13);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(89	,'3'	,'Tanzania'	,55.51);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(90	,'-8'	,'Jordan'	,54.44);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(91	,'12'	,'Laos'	,54.29);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(92	,'4'	,'Moldova',	53.74);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(93	,'-'	,'Honduras',	52.5);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(94	,'-9'	,'CÃ´te dIvoire',	47.02);
INSERT  INTO MobileData (MID, RankChange, Country, Mbps) VALUES(95	,'2'	,'Lebanon'	,45.04);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(96	,'6'	,'Kyrgyzstan'	,44.18);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(97	,'8'	,'Jamaica'	,44.05);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(98	,'1'	,'Angola	',43.94);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(99	,'9'	,'Somalia',	43.5);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(100	,'4'	,'Armenia',	42.64);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(101	,'-'	,'Sri Lanka',	41.97);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(102	,'4'	,'Iraq',	41.64);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(103	,'17'	,'Fiji',	41.09);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(104	,'17'	,'Mozambique	',40.9);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(105	,'2'	,'Tunisia	',40.4);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(106	,'3'	,'Russia'	,39.96);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(107	,'-7'	,'Trinidad and Tobago',	39.34);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(108	,'9'	,'Indonesia	',38.12);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(109	,'3'	,'Cambodia'	,37.9);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(110	,'8'	,'Ukraine	',37.63);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(111	,'2'	,'El Salvador',	37.43);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(112	,'4'	,'Egypt'	,36.75);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(113	,'1'	,'Algeria',	36.72);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(114	,'-16',	'Zambia',	36.59);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(115	,'7'	,'Myanmar (Burma)',	34.98);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(116	,'-1'	,'Bosnia and Herzegovina',	34.5);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(117	,'-6'	,'Ecuador'	,33.9);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(118	,'5'	,'Bangladesh	',33.77);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(119	,'-'	,'Papua New Guinea',	32.71);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(120	,'5'	,'Peru'	,30.82);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(121	,'6'	,'Panama'	,29.73);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(122	,'6'	,'Nicaragua',	29.09);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(123	,'3'	,'Namibia'	,28.98);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(124	,'-'	,'Ghana'	,28.66);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(125	,'4'	,'Rwanda'	,27.25);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(126	,'5'	,'DR Congo',	27.17);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(127	,'5'	,'Belarus'	,26.89);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(128	,'2'	,'Paraguay'	,25.89);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(129	,'4'	,'Pakistan'	,25.75);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(130	,'7'	,'Nepal'	,22.45);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(131	,'8'	,'Syria'	,21.62);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(132	,'2'	,'Libya'	,21.38);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(133	,'2'	,'Cameroon',20.93);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(134	,'7'	,'Sudan'	,20.9);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(135	,'5',	'Venezuela',	20.88);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(136	,'2'	,'Mongolia',	19.6);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(137	,'-1'	,'Tajikistan',	19.36);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(138	,'4'	,'Bolivia'	,18.72);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(139	,'5'	,'Haiti'	,17.79);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(140	,'3'	,'Belize'	,16.88);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(141	,'4',	'East Timor',13.59);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(142,	'4',	'Yemen',	9.66);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(143,	'5',	'Cuba',	9.29);
INSERT INTO MobileData (MID, RankChange, Country, Mbps) VALUES(144,	'3',	'Afghanistan',9.14);
Select * from MobileData;